import { type MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://nexbaron.com";

  const routes: Array<{
    path: string;
    priority: number;
    changeFrequency: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  }> = [
    { path: "", priority: 1, changeFrequency: "monthly" },
    { path: "/digital", priority: 0.9, changeFrequency: "weekly" },
    { path: "/print", priority: 0.9, changeFrequency: "weekly" },
    { path: "/print/quote", priority: 0.9, changeFrequency: "weekly" },
    { path: "/digital/pricing", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/who-we-help", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/restaurants", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/cafes", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/bakeries", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/hotels", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/salons", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/spas", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/gyms", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/clinics", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/multi-speciality", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/tutors", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/coaching", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/schools", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/kirana", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/boutiques", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/supermarkets", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/pharmacies", priority: 0.7, changeFrequency: "monthly" },
    {
      path: "/digital/who-we-help/plumbers-electricians",
      priority: 0.7,
      changeFrequency: "monthly",
    },
    { path: "/digital/who-we-help/laundry", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/car-service", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/law-ca", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/real-estate", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/photographers", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/event-planners", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/who-we-help/startups", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/automation", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/solutions", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/web-design", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/local-seo", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/social-media", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/online-ads", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/website-care", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/results", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/process", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/why-nexbaron", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/about", priority: 0.8, changeFrequency: "monthly" },
    { path: "/digital/faq", priority: 0.7, changeFrequency: "monthly" },
    { path: "/digital/contact", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products", priority: 0.8, changeFrequency: "monthly" },
    { path: "/print/products/visiting-cards", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/card-holders", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/pamphlets-posters", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/tags", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/files", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/letter-heads", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/envelopes", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/digital-paper-printing", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/atm-pouches", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/bill-books", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/stickers-labels", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/pens", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/shooting-targets", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/products/sample-files", priority: 0.7, changeFrequency: "monthly" },
    { path: "/print/specifications", priority: 0.6, changeFrequency: "monthly" },
    { path: "/print/about", priority: 0.6, changeFrequency: "monthly" },
    { path: "/print/contact", priority: 0.6, changeFrequency: "monthly" },
    { path: "/about", priority: 0.6, changeFrequency: "monthly" },
    { path: "/privacy", priority: 0.2, changeFrequency: "yearly" },
    { path: "/terms", priority: 0.2, changeFrequency: "yearly" },
    { path: "/refund", priority: 0.2, changeFrequency: "yearly" },
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route.path}`,
    lastModified: new Date(),
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
